name: conda

on:
  workflow_dispatch:
  push:
     branches:
       - main

jobs:
  build:
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      # - name: install
      #   run:  |
      #     sudo apt-get update
      #     sudo apt-get install \
      #     autoconf automake autoconf-archive doxygen \
      #     libboost-dev libboost-fiber-dev libboost-regex-dev \
      #     libelf-dev openmpi-bin openmpi-common mpi-default-dev python3-dev
      - name: miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.12.9
          channels: conda-forge,iowarp
      - name: build-conda
        run: |
          env
          conda install -y conda-build
          conda install -y conda-verify
          conda install -y anaconda-client
          conda-build .
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: scspkg-0.0.0-py312_0.conda
          path: /usr/share/miniconda/envs/test/conda-bld/linux-64/scspkg-0.0.0-py312_0.conda
      - name: release
        run: |
          anaconda -t  "${{ secrets.ANACONDA_TOKEN }}" upload /usr/share/miniconda/envs/test/conda-bld/linux-64/scspkg-0.0.0-py312_0.conda
